name: tests
on:
  pull_request:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          # install project deps if present (case-insensitive)
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f Requirements.txt ]; then
            pip install -r Requirements.txt
          fi
          # always ensure pytest is available (and common libs your code uses)
          pip install --upgrade pytest numpy pandas yfinance matplotlib pandas-datareader statsmodels lxml

      - name: Run tests
        run: python -m pytest -q
