name: tests
on:
  pull_request:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f Requirements.txt ]; then
            pip install -r Requirements.txt
          else
            # minimal deps to import the module + run tests
            pip install pytest numpy pandas yfinance matplotlib pandas-datareader statsmodels
          fi
      - name: Run tests
        run: python -m pytest -q
